repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch # prevent direct commits to main branch
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1024]
        exclude: uv.lock

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [tomli]

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor

  - repo: local
    hooks:
      - id: lint
        name: Ruff Lint
        entry: make
        args: [lint]
        types: [python]
        language: system
        pass_filenames: false
      - id: format
        name: Ruff Format
        entry: make
        args: [format]
        types: [python]
        language: system
        pass_filenames: false
      - id: typecheck
        name: Pyright
        entry: make
        args: [typecheck]
        types: [python]
        language: system
        pass_filenames: false
